---
engines:
  pylint:
    # PyLint code quality is already measured and reported via TravisCI across
    # multiple Pythons.  It is wasteful to run yet another PyLint, especially
    # one that fails to honor the project's .pylintrc file and cannot run
    # against a matrix of Pythons.
    enabled: false

exclude_paths:
  # Codacy fails to comprehend PyTests.
  - 'tests/**'

  # MarkDown files are not project source code.
  - '**/*.md'

  # Codacy fails to comprehend imports used elsewhere.
  - '**/__init__.py'
