sudo: false

language:
  - python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install ruamel.yaml pytest pytest-cov pycodestyle

script:
  - pytest --verbose --cov=yamlpath --cov-report=term-missing tests
  - pycodestyle yamlpath
  - pip install .

notifications:
  email: false
