sudo: false

language:
  - python

python:
  - 3.6

install:
  - pip install --upgrade ruamel.yaml pytest pytest-cov pycodestyle

script:
  - pip install .
  - pytest --verbose --cov=yamlpath --cov-report=term-missing tests
  - pycodestyle yamlpath

notifications:
  email: false
