sudo: false

language:
  - python

python:
  - 3.6

install:
  - pip install --upgrade ruamel.yaml pytest pytest-cov pycodestyle
  - gem install hiera-eyaml

script:
  - pip install -e .
  - pytest --cov=yamlpath --cov-report=html --cov-report=term-missing tests
  - pycodestyle yamlpath

notifications:
  email: false
