sudo: false

language:
  - python

python:
  - 3.6

install:
  - pip install --upgrade ruamel.yaml pytest pytest-cov pycodestyle
  - gem install hiera-eyaml

script:
  - pip install -e .
  - pytest --verbose --cov --cov-report=term-missing --cov-fail-under=90 tests
  - pycodestyle yamlpath

notifications:
  email: false
