# SOURCE:  https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Upload Python TEST Package

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - feature/*
      - bugfix/*
      - issue/*
  pull_request:
    branches:
      - master
      - development
      - release/*

jobs:
  test-publish:
    name: Publish to TEST PyPI
    runs-on: ubuntu-latest
    environment: 'Configure PyPI: Test'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Build Tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
    - name: Build Artifacts
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish Artifacts
      run: |
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
